# Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/assets/mkdocs/mkdocs.yml
# See: https://www.mkdocs.org/user-guide/configuration/

site_name: Arduino Firmware Uploader
site_description: A firmware uploader/updater for Arduino Boards.
site_url: https://arduino.github.io/arduino-fwuploader/

repo_name: arduino/arduino-fwuploader
repo_url: https://github.com/arduino/arduino-fwuploader
edit_uri: blob/main/docs/

copyright: Copyright 2021 ARDUINO SA (http://www.arduino.cc/)

theme:
  name: material
  logo: img/icon_mac_light.png
  palette:
    primary: teal
    accent: orange

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.toc:
      permalink: true
  - mdx_truly_sane_lists:
      nested_indent: 2
      truly_sane: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
      emoji_index: !!python/name:pymdownx.emoji.twemoji
  - pymdownx.magiclink:
      repo: arduino-fwuploader
      repo_url_shorthand: true
      user: arduino
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Configure Material theme for versioning
extra:
  version:
    provider: mike

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Command reference:
      - arduino-fwuploader: commands/arduino-fwuploader.md
      - certificates: commands/arduino-fwuploader_certificates.md
      - certificates flash: commands/arduino-fwuploader_certificates_flash.md
      - firmware: commands/arduino-fwuploader_firmware.md
      - firmware flash: commands/arduino-fwuploader_firmware_flash.md
      - firmware get-version: commands/arduino-fwuploader_firmware_get-version.md
      - firmware list: commands/arduino-fwuploader_firmware_list.md
      - version: commands/arduino-fwuploader_version.md
