= Firmware/Certificates updater for the Arduino WiFi 101 Shield =

Use this tool to update the SSL root-certificates installed on the
WiFi 101 shield.

== Usage ==

1. Upload the https://github.com/arduino-libraries/WiFi101/tree/master/examples/FirmwareUpdater[FirmwareUpdater]
   sketch onto your board. You need to install the lastest WiFi101 library
   (available through the library manager of the Arduino IDE). The sketch is
   included as an example of the library, 
   ```File -> Examples -> WiFi101 -> FirmwareUpdater```.
2. Run "winc1500-uploader-gui".
3. The tools is able to fetch root certificates directly from the
   websites, just write the IP or domain in the text box and click
   on the "Fetch" button.
4. Select the serial port of the board running the "FirmwareUploader"
   sketch.
5. Click "Update" button.

== How to build ==

 go get go.bug.st/serial
 go build src/github.com/arduino-libraries/WiFi101-FirmwareUpdater/cli/main/winc1500-uploader.go

 go get github.com/google/gxui
 go get github.com/google/gxui/drivers/gl
 go get github.com/google/gxui/gxfont
 go get github.com/google/gxui/math
 go get github.com/google/gxui/samples/flags
 go build src/github.com/arduino-libraries/WiFi101-FirmwareUpdater/gui/main/winc1500-uploader-gui.go

== License ==

Copyright (c) 2015 Arduino LLC. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
