= Firmware/Certificates updater for WINC and NINA Wifi module =

Use this tool to update the firmware and/or add SSL certificates for any WINC or NINA modules

== Install ==

You can download the Firmware/Certificates updater here:

https://github.com/bcmi-labs/WiFi-FirmwareUpdater-cli/releases/latest

== Usage ==

Extract the zip file and run (for example, NINA -> WiFi1010)

 ./$your_os/updater -flasher firmwares/NINA/FirmwareUpdater.mkrwifi1010.ino.bin -firmware firmwares/NINA/1.2.1/NINA_W102.bin -port /dev/ttyACM0  -address arduino.cc:443 -restore_binary /tmp/arduino_build_619137/WiFiSSLClient.ino.bin -programmer {runtime.tools.bossac}/bossac

To flash a MKR1000:

 ./$your_os/updater -flasher firmwares/WINC1500/FirmwareUpdater.mkr1000.ino.bin -firmware firmwares/WINC1500/19.5.4/m2m_aio_3a0.bin -port /dev/ttyACM0  -address arduino.cc:443 -restore_binary /tmp/arduino_build_619137/WiFiSSLClient.ino.bin -programmer {runtime.tools.bossac}/bossac

=== Command line options ===

The full list of command line options can be obtained with the `-h` option: `./updater -h` 

   Usage of ./distrib/linux64/updater:
     -address value
         address (host:port) to fetch and flash root certificate for, multiple values allowed
     -certs string
         root certificate directory
     -firmware string
         firmware file to flash
     -flasher string
         firmware upload binary (precompiled for the right target) -> if not provided it will expect FirmwareUpdater sketch to be already flashed on the board
     -model string
         module model (winc or nina)
     -port string
         serial port to use for flashing
     -programmer string
         path of programmer in use (avrdude/bossac)
     -read
         read all firmware and output to stdout
     -restore_binary string
         firmware upload binary (precompiled for the right target) -> if not provided it will try to restore the original firmware

== How to build the tools from source file ==

 go get src/github.com/arduino-libraries/WiFi101-FirmwareUpdater/cli/main/
 # important! navigate to src/github.com/facchinm/go-serial/ and checkout branch v1 !
 # to be solved by vendoring the dependencies
 go build src/github.com/arduino-libraries/WiFi101-FirmwareUpdater/cli/main/

== License ==

Copyright (c) 2015-2016 Arduino LLC. All right reserved.

This library is free software; you can redistribute it and/or
modify it under the terms of the GNU Lesser General Public
License as published by the Free Software Foundation; either
version 2.1 of the License, or (at your option) any later version.

This library is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
Lesser General Public License for more details.

You should have received a copy of the GNU Lesser General Public
License along with this library; if not, write to the Free Software
Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA

