# Source: https://github.com/arduino/tooling-project-assets/blob/main/workflow-templates/test-go-task.md
name: Test Go

env:
  # See: https://github.com/actions/setup-go/tree/v2#readme
  GO_VERSION: "1.15"

# See: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows
on:
  push:
    paths:
      - ".github/workflows/test-go-task.ya?ml"
      - "codecov.ya?ml"
      - "**/go.mod"
      - "**/go.sum"
      - "Taskfile.ya?ml"
      - "**.go"
      - "**/testdata/**"
  pull_request:
    paths:
      - ".github/workflows/test-go-task.ya?ml"
      - "codecov.ya?ml"
      - "**/go.mod"
      - "**/go.sum"
      - "Taskfile.ya?ml"
      - "**.go"
      - "**/testdata/**"
  workflow_dispatch:
  repository_dispatch:

jobs:
  test:
    name: test (${{ matrix.module.path }} - ${{ matrix.operating-system }})

    strategy:
      fail-fast: false

      matrix:
        operating-system:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        module:
          - path: ./
            codecov-flags: unit

    runs-on: ${{ matrix.operating-system }}

    steps:
      # By default, actions/checkout converts the repo's LF line endings to CRLF on the Windows runner.
      - name: Disable EOL conversions
        run: git config --global core.autocrlf false

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Install Task
        uses: arduino/setup-task@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          version: 3.x

      - name: Run tests
        env:
          GO_MODULE_PATH: ${{ matrix.module.path }}
        run: task go:test

      - name: Send unit tests coverage to Codecov
        if: runner.os == 'Linux'
        uses: codecov/codecov-action@v2
        with:
          file: ${{ matrix.module.path }}coverage_unit.txt
          flags: ${{ matrix.module.codecov-flags }}
          fail_ci_if_error: ${{ github.repository == 'arduino/arduino-fwuploader' }}
